// Generates src/version.js with the current version and build datetime.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const datetime = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}`;

const content = `// Auto-generated by \`npm run stamp\` — do not edit manually
export const VERSION = "v${pkg.version} \u00b7 ${datetime}";
`;

writeFileSync(join(root, 'src', 'version.js'), content);
console.log(`Stamped: v${pkg.version} \u00b7 ${datetime}`);
